
import { api, firstErrorMessage, formatCurrency, getAccessToken, resolveMediaUrl, restoreSession } from "../api.js";
import { getGuestCartItems, guestCartCount, removeGuestItem, updateGuestItem } from "../guest-cart.js";
import { renderFooter, renderNav } from "../nav.js";
import { setState } from "../state.js";
import { showToast } from "../toast.js";

renderNav(); renderFooter();
const container=document.getElementById("cart-container"); let authenticated=false;
function escapeHtml(value){const div=document.createElement("div");div.textContent=value??"";return div.innerHTML;}
function itemImage(item){return resolveMediaUrl(item.product_image||item.primary_image||item.image);}
function lineTemplate(item){const image=itemImage(item);const key=authenticated?item.id:item.key;return `<article class="cart-line" data-key="${escapeHtml(key)}"><a href="/product.html?slug=${encodeURIComponent(item.product_slug||"")}" class="cart-line__image${image?"":" product-visual--empty"}" data-label="AMBLE">${image?`<img src="${escapeHtml(image)}" alt="${escapeHtml(item.product_name)}">`:""}</a><div class="cart-line__body"><p class="cart-line__category">${escapeHtml(item.product_category||"AMBLE")}</p><a href="/product.html?slug=${encodeURIComponent(item.product_slug||"")}" class="cart-line__name">${escapeHtml(item.product_name)}</a>${item.variant_label?`<p class="cart-line__variant">${escapeHtml(item.variant_label)}${item.variant_sku?` · ${escapeHtml(item.variant_sku)}`:""}</p>`:""}<p class="cart-line__price">${formatCurrency(item.unit_price)} each</p><div class="cart-line__controls"><div class="stepper"><button class="qty-minus">−</button><input class="qty-input" type="number" min="1" max="${item.available_stock||99}" value="${item.quantity}"><button class="qty-plus">+</button></div><button class="cart-line__remove">Remove</button></div></div><p class="cart-line__subtotal">${formatCurrency(Number(item.unit_price)*Number(item.quantity))}</p></article>`;}
function cartFromGuest(){const items=getGuestCartItems();return {items,item_count:guestCartCount(),total:items.reduce((sum,item)=>sum+Number(item.unit_price)*Number(item.quantity),0)};}
async function hydrateGuest(){const items=getGuestCartItems();await Promise.all(items.map(async(item)=>{try{const product=await api.get(`/catalog/products/${encodeURIComponent(item.product_slug)}/`);const variant=product.variants?.find((v)=>v.id===item.variant);item.in_stock=variant?variant.in_stock:product.in_stock;item.available_stock=variant?variant.stock_quantity:product.available_stock;item.unit_price=variant?variant.price:product.price;item.product_name=product.name;}catch{item.in_stock=false;}}));return cartFromGuest();}
async function load(){container.innerHTML='<div class="skeleton skeleton-line" style="height:160px"></div>';await restoreSession();authenticated=Boolean(getAccessToken());try{const cart=authenticated?await api.get("/cart/"):await hydrateGuest();render(cart);}catch(e){container.innerHTML=`<div class="state-message"><div class="state-message__inner"><h2>Couldn't load your cart</h2><p>${escapeHtml(firstErrorMessage(e))}</p><button class="btn btn--primary" id="retry-cart">Try again</button></div></div>`;document.getElementById("retry-cart")?.addEventListener("click",load);}}
function render(cart){if(!cart.items?.length){container.innerHTML='<div class="state-message"><div class="state-message__inner"><h2>Your cart is waiting</h2><p>Add something from the collection.</p><a class="btn btn--primary" href="/index.html#collection">Browse products</a></div></div>';setState({cartCount:0});return;}const unavailable=cart.items.some((item)=>item.in_stock===false);container.innerHTML=`<div class="cart-layout"><section>${!authenticated?'<div class="reliability-alert"><div><strong>Guest checkout is available.</strong><br>Your cart is stored only in this browser.</div><a class="btn btn--secondary" href="/login.html">Log in</a></div>':""}${unavailable?'<div class="reliability-alert reliability-alert--danger">One or more items are unavailable.</div>':""}<div class="cart-lines">${cart.items.map(lineTemplate).join("")}</div></section><aside class="order-summary"><h2 class="order-summary__title">Order summary</h2><div class="summary-row"><span>Subtotal (${cart.item_count})</span><span>${formatCurrency(cart.total)}</span></div><div class="summary-row"><span>Delivery</span><span>Calculated at checkout</span></div><div class="summary-row summary-row--total"><span>Total before delivery</span><span>${formatCurrency(cart.total)}</span></div>${unavailable?'<button class="btn btn--primary btn--block" disabled>Resolve unavailable items</button>':'<a class="btn btn--primary btn--block" href="/checkout.html">Continue to checkout</a>'}</aside></div>`;setState({cartCount:Number(cart.item_count)});wire();}
function wire(){container.querySelectorAll(".cart-line").forEach((line)=>{const key=line.dataset.key;const input=line.querySelector(".qty-input");const change=async(value)=>{const qty=Math.max(1,Math.min(Number(input.max||99),Number(value)||1));input.value=qty;try{if(authenticated)await api.patch(`/cart/items/${key}/`,{quantity:qty});else updateGuestItem(key,qty);await load();}catch(e){showToast(firstErrorMessage(e),"error");}};line.querySelector(".qty-minus").addEventListener("click",()=>change(Number(input.value)-1));line.querySelector(".qty-plus").addEventListener("click",()=>change(Number(input.value)+1));input.addEventListener("change",()=>change(input.value));line.querySelector(".cart-line__remove").addEventListener("click",async()=>{try{if(authenticated)await api.delete(`/cart/items/${key}/`);else removeGuestItem(key);showToast("Removed from cart");await load();}catch(e){showToast(firstErrorMessage(e),"error");}});});}
load();
