
import { api, firstErrorMessage, formatCurrency, getAccessToken, resolveMediaUrl, restoreSession } from "../api.js";
import { getGuestCartItems } from "../guest-cart.js";
import { renderFooter, renderNav } from "../nav.js";
import { setState } from "../state.js";

renderNav(); renderFooter();
const container=document.getElementById("checkout-container");let authenticated=false;let currentCart=null;let methods=[];let addresses=[];let coupon=null;let submitting=false;
function escapeHtml(value){const div=document.createElement("div");div.textContent=value??"";return div.innerHTML;}
function guestCart(){const items=getGuestCartItems().map((item)=>({...item,subtotal:String(Number(item.unit_price)*Number(item.quantity))}));return{items,item_count:items.reduce((n,i)=>n+Number(i.quantity),0),total:String(items.reduce((n,i)=>n+Number(i.unit_price)*Number(i.quantity),0))};}
async function hydrateGuest(){const cart=guestCart();await Promise.all(cart.items.map(async(item)=>{const product=await api.get(`/catalog/products/${encodeURIComponent(item.product_slug)}/`);const variant=product.variants?.find((v)=>v.id===item.variant);item.product=product.id;item.product_name=product.name;item.product_image=resolveMediaUrl(product.images?.[0]?.image);item.in_stock=variant?variant.in_stock:product.in_stock;item.available_stock=variant?variant.stock_quantity:product.available_stock;item.unit_price=variant?variant.price:product.price;item.subtotal=String(Number(item.unit_price)*Number(item.quantity));}));cart.total=String(cart.items.reduce((n,i)=>n+Number(i.subtotal),0));return cart;}
async function load(){container.innerHTML='<div class="skeleton skeleton-line" style="height:420px"></div>';await restoreSession();authenticated=Boolean(getAccessToken());try{currentCart=authenticated?await api.get("/cart/"):await hydrateGuest();if(!currentCart.items?.length)return renderEmpty();[methods,addresses]=await Promise.all([api.get(`/orders/shipping-methods/?subtotal=${encodeURIComponent(currentCart.total)}`),authenticated?api.get("/orders/addresses/").catch(()=>[]):Promise.resolve([])]);render();}catch(e){container.innerHTML=`<div class="state-message"><div class="state-message__inner"><h1>Couldn't load checkout</h1><p>${escapeHtml(firstErrorMessage(e))}</p><button class="btn btn--primary" id="retry">Try again</button></div></div>`;document.getElementById("retry")?.addEventListener("click",load);}}
function renderEmpty(){container.innerHTML='<div class="state-message"><div class="state-message__inner"><h1>Your cart is empty</h1><a class="btn btn--primary" href="/index.html">Browse products</a></div></div>';}
function methodFee(method){return Number(method?.calculated_fee??method?.fee??0);}
function selectedMethod(){return methods.find((m)=>String(m.id)===document.getElementById("shipping_method_id")?.value)||methods[0];}
function totals(){const subtotal=Number(currentCart.total);const discount=Number(coupon?.discount_amount||0);const fee=methodFee(selectedMethod());return{subtotal,discount,fee,total:Math.max(0,subtotal-discount)+fee};}
function itemTemplate(item){return `<div class="checkout-item"><div class="checkout-item__image${item.product_image?"":" product-visual--empty"}">${item.product_image?`<img src="${escapeHtml(resolveMediaUrl(item.product_image))}" alt="${escapeHtml(item.product_name)}">`:""}</div><div><p class="checkout-item__name">${escapeHtml(item.product_name)}</p>${item.variant_label?`<p class="checkout-item__meta">${escapeHtml(item.variant_label)}</p>`:""}<p class="checkout-item__meta">Quantity ${item.quantity}</p></div><p class="checkout-item__price">${formatCurrency(item.subtotal)}</p></div>`;}
function render(){const defaultMethod=methods.find((m)=>m.is_default)||methods[0];const defaultAddress=addresses.find((a)=>a.is_default);container.innerHTML=`<nav class="breadcrumbs"><a href="/index.html">Shop</a><span class="breadcrumbs__sep"></span><a href="/cart.html">Cart</a><span class="breadcrumbs__sep"></span><span>Checkout</span></nav><div class="page-heading"><div><p class="page-heading__eyebrow">Secure payment</p><h1 class="page-title">Checkout</h1></div><p class="page-subtitle">Pay with PayShap. Local development uses a safe payment simulator.</p></div>
<div class="checkout-layout"><section class="checkout-card"><form class="form" id="checkout-form">
${!authenticated?'<div class="checkout-card__head"><span class="checkout-card__step">01</span><h2 class="checkout-card__title">Contact</h2></div><div class="form-field"><label for="guest_email">Email for receipt</label><input id="guest_email" name="guest_email" type="email" autocomplete="email" required></div>':""}
<div class="checkout-card__head checkout-card__head--section"><span class="checkout-card__step">${authenticated?'01':'02'}</span><h2 class="checkout-card__title">Delivery details</h2></div>
${addresses.length?`<div class="form-field"><label for="shipping_address_id">Saved address</label><select id="shipping_address_id" name="shipping_address_id"><option value="">Enter a new address</option>${addresses.map((a)=>`<option value="${a.id}" ${defaultAddress?.id===a.id?'selected':''}>${escapeHtml(a.label)} — ${escapeHtml(a.address_line1)}, ${escapeHtml(a.city)}</option>`).join("")}</select></div>`:""}
<div id="new-address-fields"><div class="form-field"><label for="shipping_full_name">Full name</label><input id="shipping_full_name" name="shipping_full_name" autocomplete="name" required></div><div class="form-field"><label for="shipping_phone_number">Phone number</label><input id="shipping_phone_number" name="shipping_phone_number" type="tel" autocomplete="tel"></div><div class="form-field"><label for="shipping_address_line1">Street address</label><input id="shipping_address_line1" name="shipping_address_line1" required></div><div class="form-field"><label for="shipping_address_line2">Address line 2</label><input id="shipping_address_line2" name="shipping_address_line2"></div><div class="form-field form-field--split"><div class="form-field"><label for="shipping_city">City</label><input id="shipping_city" name="shipping_city" required></div><div class="form-field"><label for="shipping_province">Province</label><input id="shipping_province" name="shipping_province"></div></div><div class="form-field form-field--split"><div class="form-field"><label for="shipping_postal_code">Postal code</label><input id="shipping_postal_code" name="shipping_postal_code" required></div><div class="form-field"><label for="shipping_country">Country</label><input id="shipping_country" name="shipping_country" value="South Africa" required></div></div>${authenticated?'<label class="commerce-check"><input type="checkbox" name="save_address" value="true"><span>Save this address</span></label><div class="form-field"><label for="address_label">Address label</label><input id="address_label" name="address_label" value="Home"></div>':""}</div>
<div class="checkout-card__head checkout-card__head--section"><span class="checkout-card__step">${authenticated?'02':'03'}</span><h2 class="checkout-card__title">Delivery method</h2></div><div class="form-field"><label for="shipping_method_id">Shipping option</label><select id="shipping_method_id" name="shipping_method_id">${methods.map((m)=>`<option value="${m.id}" ${m.id===defaultMethod.id?'selected':''}>${escapeHtml(m.name)} — ${methodFee(m)===0?'Free':formatCurrency(methodFee(m))}</option>`).join("")}</select><p class="form-note" id="shipping-estimate"></p></div>
<div class="checkout-card__head checkout-card__head--section"><span class="checkout-card__step">${authenticated?'03':'04'}</span><h2 class="checkout-card__title">Coupon & payment</h2></div><div class="coupon-row"><div class="form-field"><label for="coupon_code">Discount code</label><input id="coupon_code" name="coupon_code" autocomplete="off"></div><button class="btn btn--secondary" type="button" id="apply-coupon">Apply</button></div><p class="form-note" id="coupon-message"></p><div class="payment-choice"><strong>PayShap</strong><span>Approve the request securely in your banking app.</span></div><p class="form-error" id="form-error" role="alert"></p><button class="btn btn--primary btn--block" id="submit-button">Continue to PayShap</button></form></section>
<aside class="order-summary"><h2 class="order-summary__title">Your order</h2><div class="checkout-items">${currentCart.items.map(itemTemplate).join("")}</div><div class="summary-row"><span>Subtotal</span><span>${formatCurrency(currentCart.total)}</span></div><div class="summary-row" id="discount-row" hidden><span>Discount</span><span id="summary-discount"></span></div><div class="summary-row"><span>Delivery</span><span id="summary-delivery"></span></div><div class="summary-row summary-row--total"><span>Total</span><span id="summary-total"></span></div><p class="secure-note">Payment is confirmed by the Django backend, not by a browser redirect.</p></aside></div>`;
  document.getElementById("checkout-form").addEventListener("submit",submit);document.getElementById("shipping_method_id").addEventListener("change",updateSummary);document.getElementById("shipping_address_id")?.addEventListener("change",toggleAddress);document.getElementById("apply-coupon").addEventListener("click",applyCoupon);toggleAddress();updateSummary();}
function toggleAddress(){const select=document.getElementById("shipping_address_id");const fields=document.getElementById("new-address-fields");const saved=Boolean(select?.value);if(fields){fields.hidden=saved;fields.querySelectorAll("input").forEach((input)=>input.disabled=saved);}}
function updateSummary(){const t=totals();document.getElementById("summary-delivery").textContent=t.fee?formatCurrency(t.fee):"Free";document.getElementById("summary-total").textContent=formatCurrency(t.total);document.getElementById("summary-discount").textContent=`−${formatCurrency(t.discount)}`;document.getElementById("discount-row").hidden=!t.discount;document.getElementById("shipping-estimate").textContent=selectedMethod()?.estimated_delivery?`Estimated: ${selectedMethod().estimated_delivery}`:"";document.getElementById("submit-button").textContent=`Continue to PayShap · ${formatCurrency(t.total)}`;}
async function applyCoupon(){const code=document.getElementById("coupon_code").value.trim();const message=document.getElementById("coupon-message");if(!code){coupon=null;message.textContent="";return updateSummary();}try{coupon=await api.post("/orders/coupons/validate/",{code,subtotal:currentCart.total});message.textContent=`${coupon.code} applied: save ${formatCurrency(coupon.discount_amount)}.`;updateSummary();}catch(e){coupon=null;message.textContent=firstErrorMessage(e);updateSummary();}}
async function submit(event){event.preventDefault();if(submitting)return;const form=event.currentTarget;if(!form.checkValidity())return form.reportValidity();submitting=true;const button=document.getElementById("submit-button");button.disabled=true;button.textContent="Creating secure payment…";const values=Object.fromEntries(new FormData(form));const payload={shipping_method_id:Number(values.shipping_method_id),coupon_code:coupon?.code||values.coupon_code||""};if(!authenticated){payload.guest_email=values.guest_email;payload.items=currentCart.items.map((item)=>({product:Number(item.product),variant:item.variant?Number(item.variant):null,quantity:Number(item.quantity)}));}if(values.shipping_address_id)payload.shipping_address_id=Number(values.shipping_address_id);else Object.assign(payload,{shipping_full_name:values.shipping_full_name,shipping_phone_number:values.shipping_phone_number||"",shipping_address_line1:values.shipping_address_line1,shipping_address_line2:values.shipping_address_line2||"",shipping_city:values.shipping_city,shipping_province:values.shipping_province||"",shipping_postal_code:values.shipping_postal_code,shipping_country:values.shipping_country,save_address:values.save_address==="true",address_label:values.address_label||"Home"});try{const result=await api.post("/orders/checkout/",payload,{timeoutMs:25000});if(authenticated)setState({cartCount:0});sessionStorage.setItem("amble:last-order",JSON.stringify(result));if(result.payment?.redirect_url){location.href=result.payment.redirect_url;return;}throw new Error(result.payment_error||"Payment could not be started.");}catch(e){document.getElementById("form-error").textContent=e.message||firstErrorMessage(e);button.disabled=false;updateSummary();submitting=false;}}
load();
