
import { api, firstErrorMessage, formatCurrency, requireAuth } from "../api.js";
import { renderFooter, renderNav } from "../nav.js";
import { showToast } from "../toast.js";
renderNav();renderFooter();const container=document.getElementById("orders-container");const countEl=document.getElementById("order-count");let page=1,orders=[],next=false,total=0,timer;
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML;}function date(v){return new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});}
function card(order){const lines=order.items.map((item)=>`<div class="order-line"><span>${item.quantity} × ${esc(item.product_name)}${item.variant_label?` <small>(${esc(item.variant_label)})</small>`:""}</span><span>${formatCurrency(item.subtotal)}</span></div>`).join("");const retry=["unpaid","failed"].includes(order.payment_status)&&order.status!=="cancelled";return `<article class="order-card"><div class="order-card__header"><div><p class="order-card__eyebrow">Placed ${date(order.created_at)}</p><h2>Order #${order.id}</h2><p>${formatCurrency(order.total_amount)}</p></div><div class="order-badges"><span class="status-badge status-badge--${order.status}">${esc(order.status_label)}</span><span class="status-badge status-badge--payment">${esc(order.payment_status_label)}</span></div></div><details><summary>View details</summary><div class="order-lines">${lines}</div><div class="order-costs"><div class="summary-row"><span>Subtotal</span><span>${formatCurrency(order.subtotal_amount)}</span></div>${Number(order.discount_amount)?`<div class="summary-row"><span>Discount ${esc(order.coupon_code)}</span><span>−${formatCurrency(order.discount_amount)}</span></div>`:""}<div class="summary-row"><span>Delivery</span><span>${formatCurrency(order.shipping_fee)}</span></div><div class="summary-row summary-row--total"><span>Total</span><span>${formatCurrency(order.total_amount)}</span></div></div></details><div class="order-card__actions">${retry?`<button class="btn btn--primary" data-pay="${order.id}">Retry PayShap payment</button>`:""}${order.can_cancel?`<button class="btn btn--secondary" data-cancel="${order.id}">Cancel order</button>`:""}</div></article>`;}
function query(p){const params=new URLSearchParams({page:p});const s=document.getElementById("order-search")?.value.trim();const status=document.getElementById("order-status-filter")?.value;if(s)params.set("search",s);if(status)params.set("status",status);return params;}
async function load({p=1,append=false}={}){if(!(await requireAuth()))return;if(!append)container.innerHTML='<div class="skeleton skeleton-line" style="height:300px"></div>';try{const response=await api.get(`/orders/?${query(p)}`);const results=response.results??response;orders=append?[...orders,...results]:results;page=p;next=Boolean(response.next);total=Number(response.count??orders.length);render();}catch(e){container.innerHTML=`<p class="form-error">${esc(firstErrorMessage(e))}</p>`;}}
function render(){countEl.textContent=`${total} order${total===1?"":"s"}`;container.innerHTML=orders.length?`<div class="orders-list">${orders.map(card).join("")}</div>${next?'<button class="btn btn--secondary" id="more">Load more</button>':""}`:'<div class="state-message"><div class="state-message__inner"><h2>No orders yet</h2><a class="btn btn--primary" href="/index.html">Start shopping</a></div></div>';container.querySelectorAll("[data-pay]").forEach((b)=>b.addEventListener("click",()=>retryPay(b.dataset.pay,b)));container.querySelectorAll("[data-cancel]").forEach((b)=>b.addEventListener("click",()=>cancel(b.dataset.cancel,b)));document.getElementById("more")?.addEventListener("click",()=>load({p:page+1,append:true}));}
async function retryPay(id,button){button.disabled=true;try{const payment=await api.post("/payments/initiate/",{order_id:Number(id)});location.href=payment.redirect_url;}catch(e){showToast(firstErrorMessage(e),"error");button.disabled=false;}}
async function cancel(id,button){if(!confirm(`Cancel order #${id}?`))return;button.disabled=true;try{await api.post(`/orders/${id}/cancel/`,{});showToast("Order cancelled");load();}catch(e){showToast(firstErrorMessage(e),"error");button.disabled=false;}}
document.getElementById("order-search")?.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>load(),350);});document.getElementById("order-status-filter")?.addEventListener("change",()=>load());load();
